export const SET_SHOES = "SET_SHOES";
export const FETCH_SHOES_FAILED = "FETCH_SHOES_FAILED";

export const SELECT_SHOE = "SELECT_SHOE";
export const ADD_SHOE_TO_BASKET = "ADD_SHOE_TO_BASKET";

export const USER_SIGN_UP_INIT = "USER_SIGN_UP_INIT";
export const USER_SIGN_UP_START = "USER_SIGN_UP_START";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";

export const USER_SIGN_IN = "USER_SIGN_IN";
