export const SET_SHOES = "SET_SHOES";
export const FETCH_SHOES_FAILED = "FETCH_SHOES_FAILED";

export const SELECT_SHOE = "SELECT_SHOE";
export const ADD_SHOE_TO_BASKET = "ADD_SHOE_TO_BASKET";

export const USER_SIGN_UP = "USER_SIGN_UP";

export const SET_USERNAMES = "SET_USERNAMES";
export const FETCH_USERNAMES_FAILED = "FETCH_USERNAMES_FAILED";
export const USER_SIGN_IN = "USER_SIGN_IN";
